services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v24.2
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      COCKROACH_USER: root
      COCKROACH_PASSWORD: admin
    command: ["start-single-node", "--insecure"]
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:
    driver: local
